### ISSUE TITLE
beehives: how much rum

### ISSUE THREAD

**Issue by pgajdos** [PackageNinjas/christmas-2024#7]
I would like to have serious discussion how much rum should be there. Two years back my son was helping with creating them and put two times more rum in the dough as the recipe was saying. Beehives were way better.

**Comment by pgajdos** [comment]
cc @kstreitova

**Comment by kstreitova** [comment]
@pgajdos That's a very good point, and I have to admit I usually do the same, with the simple explanation that more is more :) I've adjusted the comment in the specfile to offer more rum options.

**Comment by pgajdos** [comment]
@kstreitova, thank you for lightning fast response and elegant solution.
