### ISSUE TITLE
English name for piškoty

### ISSUE THREAD

**Issue by mcepl** [PackageNinjas/christmas-2024#9]
https://github.com/PackageNinjas/christmas-2024/blob/f1d64ea69f7eaee9f9a173310bce4a70fa5889a2/recipes/beehives/beehives.spec#L35

Czech wikipedia for [piškoty](https://cs.wikipedia.org/wiki/Pi%C5%A1kot) leads to [ladyfingers](https://en.wikipedia.org/wiki/Ladyfinger_(biscuit)), which is “cukrářské piškoty”, not exactly the same, but pretty close, I would say.

Cc: @kstreitova

**Comment by kstreitova** [comment]
Thanks, @mcepl . I’ve added a bit more explanation as a comment, and I hope it’s clearer now. I must admit, though, that it might still be a challenge for people outside of Europe to find what we call dětské piškoty :)
